FROM quay.io/keycloak/keycloak:26.7.3@sha256:ff4257d0d64efbe99ed1ddfaf07765cc3c36dc7518bf8324d41961327f441c54 AS build
ENV KC_DB=postgres KC_HEALTH_ENABLED=true KC_METRICS_ENABLED=false KC_HTTP_RELATIVE_PATH=/identity
RUN /opt/keycloak/bin/kc.sh build
FROM quay.io/keycloak/keycloak:26.7.3@sha256:ff4257d0d64efbe99ed1ddfaf07765cc3c36dc7518bf8324d41961327f441c54
COPY --from=build /opt/keycloak/ /opt/keycloak/
COPY --chmod=0555 identity-start.sh /opt/keycloak/bin/signal-start.sh
USER 1000:1000
ENTRYPOINT ["/opt/keycloak/bin/signal-start.sh"]
