-- Run once with a reviewed provisioning principal in a dedicated Signal database.
-- No login passwords or default production accounts are created here.
CREATE ROLE signal_migrator NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS;
CREATE ROLE signal_identity NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS;
CREATE ROLE signal_bootstrap NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS;
CREATE ROLE signal_api NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS;
CREATE ROLE signal_scheduler NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS;
CREATE ROLE signal_authority_dispatcher NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS;
CREATE ROLE signal_release_manager NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS;
CREATE ROLE signal_workflow NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS;
CREATE ROLE signal_crawl_admission NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS;
CREATE ROLE signal_crawl_ingest NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS;

REVOKE ALL ON SCHEMA public FROM PUBLIC;
CREATE SCHEMA control AUTHORIZATION signal_migrator;
CREATE SCHEMA app AUTHORIZATION signal_migrator;
REVOKE ALL ON SCHEMA control, app FROM PUBLIC;
GRANT USAGE ON SCHEMA app TO signal_identity, signal_bootstrap, signal_api, signal_scheduler;
GRANT USAGE ON SCHEMA control
TO signal_identity, signal_bootstrap, signal_scheduler, signal_authority_dispatcher,
   signal_release_manager,
   signal_workflow,
   signal_crawl_admission, signal_crawl_ingest;
GRANT USAGE ON SCHEMA app TO signal_crawl_admission, signal_crawl_ingest;

ALTER DEFAULT PRIVILEGES FOR ROLE signal_migrator REVOKE EXECUTE ON FUNCTIONS FROM PUBLIC;
