"use client";

import { useCallback, useEffect, useState } from "react";
import { Check, FilePenLine, Plus, RefreshCw, Save, X } from "lucide-react";
import type { WriterData } from "../lib/content-writer-api";
import { readableCode } from "./home-panels";

const split=(v: FormDataEntryValue | null) => String(v??"").split(/[\n,]/).map(s=>s.trim()).filter(Boolean);

function EditorialApproval({ candidate, busy, approve }: {
  candidate: WriterData["candidates"][number];
  busy: boolean;
  approve: (values: Record<string, unknown>) => Promise<boolean>;
}) {
  const [acknowledged, setAcknowledged] = useState<string[]>([]);
  const grounding = candidate.manifest.grounding as WriterData["drafts"][number]["result"]["grounding"];
  if (candidate.delivery_approval_id) return <p>PR delivery approved. Decision {candidate.delivery_approval_id}</p>;
  if (!grounding || !Array.isArray(grounding.sentences) || grounding.sentences.some(s =>
    typeof s.path !== "string" || typeof s.sentence !== "string" || !Array.isArray(s.reasons) ||
    s.reasons.some(reason => typeof reason !== "string"))) return null;
  const flagged = grounding.sentences.filter(s => s.reasons.length > 0);
  return <form className="brain-form editorial-approval" onSubmit={e => {
    e.preventDefault();
    void approve({ candidate_id: candidate.candidate_id, revision_sha256: candidate.revision_sha256,
      acknowledged_sentences: acknowledged });
  }}>
    {flagged.map(s => <label className="writer-checkbox" key={s.path}>
      <input type="checkbox" checked={acknowledged.includes(s.path)} onChange={e =>
        setAcknowledged(current => e.target.checked ? [...current, s.path] : current.filter(path => path !== s.path))} />
      <span>I acknowledge: {s.sentence} ({s.reasons.map(r=>readableCode(r)).join(", ")})</span>
    </label>)}
    <p>Dashboard approval requires MFA authenticated within five minutes. Merge and deployment remain external.</p>
    <button disabled={busy || flagged.some(s => !acknowledged.includes(s.path))}>
      <Check size={16} />Approve PR delivery
    </button>
  </form>;
}
export function ContentWriter({siteId,inbox=false,initialData}:{siteId:string;inbox?:boolean;initialData?:WriterData}) {
  const [data,setData]=useState<WriterData|null>(initialData??null);
  const [notice,setNotice]=useState("");const [busy,setBusy]=useState(false);
  const [editing,setEditing]=useState<WriterData["briefs"][number]|null>(null);
  const load=useCallback(async()=>{try {const r=await fetch(`/actions/content-writer?site_id=${siteId}`,{cache:"no-store"});if(!r.ok)throw new Error();setData(await r.json());}catch{setNotice("Articles are unavailable. Refresh to retry.");setData(null);}},[siteId]);
  useEffect(()=>{if(!initialData)void load();},[initialData,load]);
  async function act(action:string,values:Record<string,unknown>){setBusy(true);setNotice("");try{const r=await fetch("/actions/content-writer",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({schema_version:1,site_id:siteId,action,...values})});if(!r.ok)throw new Error();const result=await r.json();setNotice(readableCode(String(result.state)));await load();return true;}catch{setNotice("The request was not completed. Refresh before retrying.");return false;}finally{setBusy(false);}}
  return <div className="business-brain content-writer">
    <header className="brain-toolbar"><h2>{inbox?"Articles to review":"Briefs and drafts"}</h2><button title="Refresh Articles" aria-label="Refresh Articles" disabled={busy} onClick={()=>void load()}><RefreshCw size={16}/></button></header>
    {notice&&<p role="status">{notice}</p>}
    {!data?<p role="status">{notice?"No content loaded.":"Loading articles"}</p>:<>
      {!inbox&&<>{data.monthly_model_budget&&<p role="status">Monthly model budget: ${(data.monthly_model_budget.used_micros/1_000_000).toFixed(2)} of ${(data.monthly_model_budget.cap_micros/1_000_000).toFixed(2)}{data.monthly_model_budget.state==="unavailable" ? " - exhausted; drafting unavailable." : data.monthly_model_budget.warning ? " - 80% warning." : ""}</p>}<p role="status">{data.monthly_model_budget?.state==="unavailable"?"Drafting unavailable: monthly model budget exhausted.":data.model_state==="unavailable"?"Drafting unavailable: model provider is not configured.":"Drafting available"}</p><p role="status">{data.cap_reached?"Weekly cap reached. No new drafts.":`${data.used} of ${data.cap} drafts used in the last seven days`}</p>
      <form className="brain-form" onSubmit={e=>{e.preventDefault();void act("caps",{cap:Number(new FormData(e.currentTarget).get("cap"))});}}><label>Weekly draft cap<input name="cap" type="number" min={1} max={data.platform_maximum} key={data.cap} defaultValue={data.cap}/></label><button disabled={busy}><Save size={16}/>Save cap</button></form>
      <section className="settings-section"><h2>Briefs</h2>{!data.briefs.length&&<p>No briefs yet.</p>}<ul className="brain-facts">{data.briefs.map(b=><li key={b.brief_id}><div><h3>{b.payload.topic}</h3><p>{readableCode(b.payload.kind)} · {readableCode(b.payload.intent)} intent · “{b.payload.query}”</p><p>{readableCode(b.status)}</p><details><summary>Sources and approved facts</summary><ul>{b.payload.source_ids.map(id=><li key={id}>Crawl evidence {id}</li>)}{b.payload.fact_ids.map(id=><li key={id}><a href={`/actions/business-brain?site_id=${siteId}&resource=provenance&fact_id=${id}`} target="_blank" rel="noreferrer">Approved fact {id}</a></li>)}</ul>{b.payload.internal_links.map(url=><p key={url}>{url}</p>)}</details></div><div className="brain-actions">{b.status==="proposed"&&<button title="Accept brief" disabled={busy} onClick={()=>void act("accept-brief",{brief_id:b.brief_id})}><Check size={16}/>Accept</button>}{b.status==="accepted"&&<><button title="Draft article" disabled={busy||data.cap_reached||data.model_state!=="available"||data.monthly_model_budget?.state==="unavailable"} onClick={()=>void act("drafts",{brief_id:b.brief_id})}><FilePenLine size={16}/>Draft</button><button title="Revise brief" disabled={busy} onClick={()=>setEditing(b)}><FilePenLine size={16}/>Revise</button></>}</div></li>)}</ul>
      <details id="new-brief" open={Boolean(editing)}><summary>{editing?"Revise brief":"New brief"}</summary><form key={editing?.brief_id??"new"} className="brain-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void act("briefs",{payload:{topic:f.get("topic"),query:f.get("query"),intent:f.get("intent"),kind:f.get("kind"),source_ids:split(f.get("source_ids")),fact_ids:split(f.get("fact_ids")),internal_links:split(f.get("internal_links"))},proposal:f.get("proposal")==="on",supersedes_id:editing?.brief_id??null}).then(saved=>{if(saved)setEditing(null);});}}>
      <label>Topic<input name="topic" maxLength={200} required defaultValue={editing?.payload.topic}/></label><label>Target query<input name="query" maxLength={200} required defaultValue={editing?.payload.query}/></label><label>Intent<select name="intent" defaultValue={editing?.payload.intent??"informational"}>{["informational","commercial","navigational","transactional"].map(v=><option key={v}>{v}</option>)}</select></label><label>Work type<select name="kind" defaultValue={editing?.payload.kind??"new_article"}><option value="new_article">New article</option><option value="content_refresh">Content refresh</option></select></label><label>Crawl evidence IDs<textarea name="source_ids" required defaultValue={editing?.payload.source_ids.join("\n")}/></label><label>Approved fact IDs<textarea name="fact_ids" required defaultValue={editing?.payload.fact_ids.join("\n")}/></label><label>Planned internal links<textarea name="internal_links" defaultValue={editing?.payload.internal_links.join("\n")}/></label><label className="writer-checkbox"><input name="proposal" type="checkbox"/>Propose from crawl evidence</label><div className="brain-actions"><button disabled={busy}><Plus size={16}/>{editing?"Save revision":"Create brief"}</button>{editing&&<button type="button" onClick={()=>setEditing(null)}><X size={16}/>Cancel</button>}</div></form></details></section>
      <section className="settings-section"><h2>Drafts</h2>{!data.drafts.length&&<p>No drafts yet.</p>}<ul className="brain-facts">{data.drafts.map(d=><li key={d.draft_id}><div><h3 title={`Draft ${d.draft_id}`}>{data.briefs.find(b=>b.brief_id===d.brief_id)?.payload.topic ?? "Untitled draft"}</h3><p>{readableCode(d.result.state)}</p>{d.result.reason&&<p>{readableCode(d.result.reason)}</p>}{d.result.quality&&<><p role={d.result.quality.state==="low_quality"?"alert":undefined}>Writing quality: {readableCode(d.result.quality.state)}{d.result.quality.reasons.length ? ` - ${d.result.quality.reasons.map(r=>readableCode(r)).join(", ")}` : ""}</p><details><summary>Quality metrics</summary><pre>{JSON.stringify(d.result.quality,null,2)}</pre></details></>}{d.result.fallback&&<p>Labelled {d.result.provider==="openai_fallback"?"high-effort model":"deterministic"} fallback</p>}{d.result.originality&&<p>Originality: {readableCode(d.result.originality.state)}; 8-gram overlap {(100*d.result.originality.eight_gram_overlap).toFixed(1)}%; lexical overlap {(100*d.result.originality.lexical_window_overlap).toFixed(1)}%</p>}{d.result.grounding&&<details><summary>Claim grounding</summary><ul className="writer-claims">{d.result.grounding.sentences.map(s=><li key={s.path}><p>{s.sentence}</p><span>{s.supported?"Supported":s.reasons.map(readableCode).join(", ")}</span>{s.claims?.map((claim,index)=><div key={index}><p>{claim.text}</p><span>{readableCode(claim.status)}: {claim.reasons.map(readableCode).join(", ")}</span>{claim.fact_ids.map(id=><a key={id} href={`/actions/business-brain?site_id=${siteId}&resource=provenance&fact_id=${id}`} target="_blank" rel="noreferrer">Supporting fact {id}</a>)}</div>)}{s.fact_ids.map(id=><a key={id} href={`/actions/business-brain?site_id=${siteId}&resource=provenance&fact_id=${id}`} target="_blank" rel="noreferrer">Fact {id}</a>)}</li>)}</ul></details>}{d.result.article!==undefined&&<details><summary>Structured article</summary><pre>{JSON.stringify(d.result.article,null,2)}</pre></details>}{data.candidates.find(c=>c.draft_id===d.draft_id)?<a href="/approvals">Inbox item</a>:["grounded","owner_required"].includes(d.result.state)&&<>{data.candidate_state==="unavailable"?<p>Candidate sealing unavailable.</p>:<form className="brain-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void act("candidates",{draft_id:d.draft_id,extension_id:f.get("extension_id"),destination:f.get("destination")});}}><label>Repository format extension ID<input name="extension_id" required pattern="[0-9a-f-]{36}"/></label><label>Content file path<input name="destination" required maxLength={1024}/></label><button disabled={busy}><Check size={16}/>Seal candidate</button></form>}</>}</div></li>)}</ul></section></>}
      <section className="settings-section"><h2>Ready for your review</h2>{!data.candidates.length&&<p>No articles are waiting for review.</p>}<ul className="brain-facts">{data.candidates.map(c=><li key={c.candidate_id}><div><h3>{c.manifest.changed_files[0]?.path}</h3><p>{c.review_status==="pending"?"Waiting for your review":readableCode(c.review_status)}</p><details><summary>Exact sealed diff and evidence</summary><p>Revision <code>{c.revision_sha256}</code></p><p>A2 · Owner review · {readableCode(c.manifest.work_type)}</p><h4>Before</h4><pre>{c.manifest.changed_files[0]?.before||"New file"}</pre><h4>After</h4><pre>{c.manifest.changed_files[0]?.after}</pre><h4>Grounding and originality</h4><pre>{JSON.stringify({grounding:c.manifest.grounding,originality:c.manifest.originality},null,2)}</pre></details></div>{["pending","approved"].includes(c.review_status)&&<EditorialApproval candidate={c} busy={busy} approve={values=>act("approve-delivery",values)}/>}{c.review_status==="pending"&&<div className="brain-actions">{(["approved","changes_requested","rejected"] as const).map(decision=><button key={decision} disabled={busy} onClick={()=>void act("review",{candidate_id:c.candidate_id,revision_sha256:c.revision_sha256,decision})}>{decision==="approved"?<Check size={16}/>:<X size={16}/>} {decision==="approved"?"Approve review":decision==="rejected"?"Reject":"Request changes"}</button>)}</div>}</li>)}</ul></section>
    </>}
  </div>;
}
